eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:17001/eureka-server/eureka/

#Zipkin服务器地址
spring:
  zipkin:
    connectTimeout: 10
    readTimeout: 10
    flushInterval: 2
    baseUrl:  http://localhost:17003/
    service:
      name:  ${spring.application.name}
    compression:
      enabled: false

message:
  url: http://20.21.1.202:9080/OpenMasService?wsdl
  applicationID: test
  password : 123459