#Zipkin服务器地址 #默认http通信的配置方式
#spring:
#  zipkin:
#    connectTimeout: 10
#    readTimeout: 10
#    flushInterval: 2
#    baseUrl:  http://localhost:17003/
#    service:
#      name:  ${spring.application.name}
#    compression:
#      enabled: false

# zipkin kafka
spring:
  kafka:
    bootstrap-servers: 192.168.1.49:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 只需要 leader 许可
      acks: 1
      #重试次数.
      retries: 10

    consumer:
      group-id: message
      auto-offset-reset: latest
      enable-auto-commit: true
#      auto-commit-interval: 10
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer